#define LOG_LEVEL		LOG_LEVEL_INFO

#define BLUETOOTH_RxD	6
#define BLUETOOTH_TxD	7

#define LED_PIN			13

#define LOGGER_SERIAL_PORT Serial1

#define SERIAL_COMMS_LINK_PORT  Serial
#define SERIALCOMMS_DEFAULT_BAUD 9600

#define SERIALDEBUG_BAUD		38400

